# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
#
# https://docs.fastlane.tools/actions
default_platform(:osx)

platform :osx do
  desc "Description of what the lane does"
  lane :builddebug do
    gym(
      configuration: "Debug"
    )
  end

  lane :buildrelease do
    gym(
      configuration: "Release"
    )
  end
end

